"""
consultations/models.py
Pre-visit (SymptomForm) and post-visit (PostVisitNote) models.
"""

from django.db import models

from appointments.models import Appointment


class SymptomForm(models.Model):
    """
    Patient-submitted symptoms captured *before* the doctor visit.

    The LLM analyses the free-text symptoms and fills in ``urgency_level``,
    ``chief_complaint``, and ``suggested_questions``.  If the LLM call fails,
    ``llm_status`` is set to ``failed`` and the booking flow continues
    unblocked — the doctor simply reviews the raw text manually.
    """

    class LLMStatus(models.TextChoices):
        PENDING = "pending", "Pending"
        SUCCESS = "success", "Success"
        FAILED = "failed", "Failed"

    appointment = models.OneToOneField(
        Appointment,
        on_delete=models.CASCADE,
        related_name="symptom_form",
    )
    symptoms_text = models.TextField(
        help_text="Free-text description of the patient's symptoms.",
    )
    urgency_level = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        help_text="Low / Medium / High — populated by the LLM.",
    )
    chief_complaint = models.CharField(
        max_length=255,
        blank=True,
        help_text="Primary complaint extracted by the LLM.",
    )
    suggested_questions = models.JSONField(
        default=list,
        help_text="List of questions the patient might ask the doctor.",
    )
    llm_status = models.CharField(
        max_length=10,
        choices=LLMStatus.choices,
        default=LLMStatus.PENDING,
    )
    raw_llm_response = models.JSONField(
        null=True,
        blank=True,
        help_text="Raw JSON response from the LLM (for debugging).",
    )

    class Meta:
        app_label = "consultations"
        verbose_name = "Symptom Form"
        verbose_name_plural = "Symptom Forms"

    def __str__(self) -> str:
        return f"SymptomForm for Appointment #{self.appointment_id}"


class PostVisitNote(models.Model):
    """
    Doctor-entered clinical notes captured *after* the visit, enriched by an
    LLM to produce a patient-friendly summary with medication schedule and
    follow-up steps.
    """

    class LLMStatus(models.TextChoices):
        PENDING = "pending", "Pending"
        SUCCESS = "success", "Success"
        FAILED = "failed", "Failed"

    appointment = models.OneToOneField(
        Appointment,
        on_delete=models.CASCADE,
        related_name="post_visit_note",
    )
    clinical_notes = models.TextField(
        help_text="Doctor's clinical notes from the visit.",
    )
    prescription_text = models.TextField(
        help_text="Free-text prescription details.",
    )
    medications = models.JSONField(
        default=list,
        help_text=(
            'Structured medication list. Each item: '
            '{"name": "...", "dosage": "...", "frequency": "...", '
            '"duration_days": ...}'
        ),
    )
    patient_summary = models.TextField(
        blank=True,
        help_text="Patient-friendly summary generated by the LLM.",
    )
    follow_up_steps = models.TextField(
        blank=True,
        help_text="Follow-up instructions generated by the LLM.",
    )
    llm_status = models.CharField(
        max_length=10,
        choices=LLMStatus.choices,
        default=LLMStatus.PENDING,
    )

    class Meta:
        app_label = "consultations"
        verbose_name = "Post-Visit Note"
        verbose_name_plural = "Post-Visit Notes"

    def __str__(self) -> str:
        return f"PostVisitNote for Appointment #{self.appointment_id}"
