# Generated by Django 5.2.4 on 2026-08-23 06:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(max_length=120)),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Working hours start')),
                ('working_hours_end', models.TimeField(default=datetime.time(17, 0), verbose_name='Working hours end')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of each appointment slot in minutes.')),
                ('working_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday numbers: 0=Mon, 1=Tue, …, 6=Sun.', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive doctors won't appear in the booking flow.")),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Doctor user account')),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Leave Day',
                'verbose_name_plural': 'Leave Days',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
